### ISSUE TITLE
No highlight support for newer properties

### ISSUE THREAD

**Issue by Jaeiya** [AlanCezarAraujo/vs-code-stylus#1]
![bad-highlighting](https://cloud.githubusercontent.com/assets/2054218/11919569/ddc4860c-a70a-11e5-8c4f-f23be89a6ca4.png)

**Comment by AlanCezarAraujo** [comment]
Hi @Aedaeum!

Would you please tell me about the VS Code version?

I can't get the error on VS Code 0.10.5

Many thanks!

**Comment by AlanCezarAraujo** [comment]
After some tests, I believe the problem was resolved by the 0.10.5 update from VS Code.

**Comment by Aedaeum** [comment]
As you can see this is still an issue:
![stillanissue](https://cloud.githubusercontent.com/assets/2054218/12108935/a71eb914-b331-11e5-9459-00dbf49f8eea.png)

As you can see below, the "align-self" word is not properly applied as a "property-name":
![stillbad](https://cloud.githubusercontent.com/assets/2054218/12108970/02fa613e-b332-11e5-83c0-87ad7382d913.png)

**Comment by Jaeiya** [comment]
I just re-installed your extension and all is good, thank you :smile:
